extends SceneTree
const Reader := preload("source_snapshot.gd")
var failures: Array[String] = []
var checks := 0
var fixture_dir: String
func check(ok: bool, label: String) -> void:
	checks += 1
	if not ok: failures.append(label)
	print("[legacy-source] ", "PASS " if ok else "FAIL ", label)
func put(path: String, raw: PackedByteArray) -> void:
	var f := FileAccess.open(path, FileAccess.WRITE)
	f.store_buffer(raw)
	f.close()
func _initialize() -> void:
	fixture_dir = "user://legacy-source-" + str(Time.get_ticks_usec())
	DirAccess.make_dir_recursive_absolute(fixture_dir)
	var primary := fixture_dir.path_join("save.json")
	var backup := fixture_dir.path_join("save.bak")
	var reader := Reader.new()
	check(reader.capture(primary, backup) == {"primary": {"status":"absent"}, "backup":{"status":"absent"}}, "both absent explicit")
	check(reader.read_source(fixture_dir.path_join("missing/child")).status == "read_error", "missing parent is not absent")
	check(reader.read_source(fixture_dir).status == "read_error", "directory is not absent")
	var text := " \n{ \"version\":5, \"unknown\":9007199254740993, \"album\":[\"秋日\"], \"plant_state\":3 }\r\n"
	var original := text.to_utf8_buffer()
	put(primary, original)
	var snapshot := reader.capture(primary, backup)
	var arguments := OS.get_cmdline_user_args()
	if arguments.size() == 1:
		put(arguments[0], JSON.stringify(snapshot).to_utf8_buffer())
	check(Marshalls.base64_to_raw(snapshot.primary.base64) == original, "exact UTF8 whitespace large-integer bytes")
	check(snapshot.backup.status == "absent", "missing backup retained")
	var malformed := PackedByteArray([0xff, 0xfe, 0, 13, 10, 128])
	put(backup, malformed)
	snapshot = reader.capture(primary, backup)
	check(Marshalls.base64_to_raw(snapshot.backup.base64) == malformed, "invalid UTF8 retained before decoding")
	check(FileAccess.get_file_as_bytes(primary) == original, "primary unchanged")
	check(FileAccess.get_file_as_bytes(backup) == malformed, "backup unchanged")
	put(primary, PackedByteArray())
	check(reader.read_source(primary) == {"status":"present","base64":""}, "empty existing file is present")
	var future := "{\"version\":999}".to_utf8_buffer()
	put(primary, future)
	check(Marshalls.base64_to_raw(reader.read_source(primary).base64) == future, "future version preserved not defaulted")
	var exact := PackedByteArray()
	exact.resize(Reader.MAX_BYTES)
	exact.fill(65)
	put(primary, exact)
	check(Marshalls.base64_to_raw(reader.read_source(primary).base64) == exact, "exact byte limit preserved")
	exact.append(66)
	put(primary, exact)
	check(reader.read_source(primary) == {"status":"read_error","reason":"too_large"}, "over limit explicit rejection")
	check(FileAccess.get_file_as_bytes(primary) == exact, "oversized source unchanged")
	snapshot = reader.capture(primary, backup)
	check(snapshot.primary.status == "read_error" and snapshot.backup.status == "present", "one failure does not erase second source")
	check(DirAccess.get_files_at(fixture_dir).size() == 2, "reader creates no source/temp/default file")
	DirAccess.remove_absolute(primary)
	DirAccess.remove_absolute(backup)
	DirAccess.remove_absolute(fixture_dir)
	print("[legacy-source] checks=", checks, " failures=", failures)
	quit(0 if failures.is_empty() else 1)
