import {Decor,spots} from './model.mjs';
const model=new Decor(), $=id=>document.getElementById(id),yard=$('yard');
function paint(){for(const [id,p]of [['placed',model.placed],['ghost',model.preview]]){const el=$(id);el.hidden=!p;if(p){el.style.left=p.x*100+'%';el.style.top=p.y*100+'%';}}$('confirm').disabled=!model.preview;$('cancel').disabled=!model.preview;$('remove').disabled=!model.placed&&!model.preview;$('status').textContent=model.preview?'正在预览，可取消':model.placed?'本次已摆放，可收起或换位置':'可以一直收着，不必摆放';for(const b of yard.querySelectorAll('button'))b.hidden=model.mode!=='spots';$('instruction').textContent=model.mode==='spots'?'点击三个候选位置之一预览，也可用 Tab 选择。':'点击院景预览（下方草地实验区域）；无效位置不会改变摆放。';}
spots.forEach((p,i)=>{const b=document.createElement('button');b.textContent=i+1;b.setAttribute('aria-label','候选位置 '+(i+1));b.style.left=p.x*100+'%';b.style.top=p.y*100+'%';b.onclick=e=>{e.stopPropagation();model.choose(p);paint();};yard.append(b);});
for(const mode of ['spots','free'])$(mode).onclick=()=>{model.setMode(mode);paint();};
yard.onclick=e=>{if(model.mode!=='free')return;const r=yard.getBoundingClientRect();model.choose({x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height});paint();};
yard.onkeydown=e=>{if(e.target!==yard)return;if(e.key==='Escape')model.cancel();else if(e.key==='Enter')model.confirm();else if(model.mode==='free'&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){const p={...(model.preview||model.placed||spots[1])};p.x+=e.key==='ArrowLeft'?-.02:e.key==='ArrowRight'?.02:0;p.y+=e.key==='ArrowUp'?-.02:e.key==='ArrowDown'?.02:0;model.choose(p);}else return;e.preventDefault();paint();};
$('confirm').onclick=()=>{model.confirm();paint();};$('cancel').onclick=()=>{model.cancel();paint();};$('remove').onclick=()=>{model.remove();paint();};
$('compare').onclick=async()=>{const captured=model.placed?{...model.placed}:null;const image=new Image();image.src='../../assets/holiday/environment/yard_sunny.png';await image.decode();$('pair').replaceChildren();for(const [label,p]of [['合成预览 · 未摆放',null],['合成预览 · 当前摆放（非游戏照片）',captured]]){const box=document.createElement('div'),text=document.createElement('p'),c=document.createElement('canvas');text.textContent=label;c.width=960;c.height=540;const ctx=c.getContext('2d');ctx.drawImage(image,0,0,960,540);if(p){ctx.fillStyle='#d89638';ctx.fillRect(p.x*960-12,p.y*540-24,24,24);}box.append(text,c);$('pair').append(box);}};paint();
