const load=async path=>{const i=new Image();i.src=path;await i.decode();return i;};
const [bg,person,sheep]=await Promise.all(['environment/yard_sunny.png','characters/player.png','characters/sheep_clingy.png'].map(p=>load('../../assets/holiday/'+p)));
const root=document.querySelector('#boards');
const places=[{x:490,y:450,s:.8},{x:480,y:500,s:.9},{x:440,y:545,s:1}];
function foot(ctx,x,y){ctx.strokeStyle='#b3322a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-6,y);ctx.lineTo(x+6,y);ctx.moveTo(x,y-6);ctx.lineTo(x,y+6);ctx.stroke();}
function perspective(y){return Math.max(.65,Math.min(1.2,.8+(y-450)*.0021));}
function animal(ctx,x,y){const h=75*perspective(y);ctx.drawImage(sheep,x-h*sheep.width/sheep.height/2,y-h,h*sheep.width/sheep.height,h);foot(ctx,x,y);}
function block(ctx,p){const w=46*p.s,h=40*p.s;ctx.fillStyle='#cfc2a4';ctx.beginPath();ctx.ellipse(p.x,p.y,w*.65,7*p.s,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#bba17a';ctx.fillRect(p.x-w/2,p.y-h,w,h);ctx.strokeStyle='#493a28';ctx.lineWidth=2;ctx.strokeRect(p.x-w/2,p.y-h,w,h);ctx.fillStyle='#e1ceb0';ctx.beginPath();ctx.moveTo(p.x-w/2,p.y-h);ctx.lineTo(p.x,p.y-h-8*p.s);ctx.lineTo(p.x+w/2,p.y-h);ctx.closePath();ctx.fill();ctx.setLineDash([4,3]);ctx.strokeStyle='#493a28';ctx.strokeRect(p.x-w/2,p.y-7*p.s,w,14*p.s);ctx.setLineDash([]);foot(ctx,p.x,p.y);}
function board(title,p,placed=true,front=false){p={...p,s:perspective(p.y)};const a=document.createElement('article'),h=document.createElement('h2'),c=document.createElement('canvas');h.textContent=title;c.width=1280;c.height=720;const t=c.getContext('2d');t.drawImage(bg,0,0,1280,720);const py=front?p.y+20:p.y-20;const ax=p.x+36;if(!front)animal(t,ax,py);if(placed)block(t,{...p,s:perspective(p.y)});if(front)animal(t,ax,py);t.drawImage(person,315,450,40,99);foot(t,335,549);t.fillStyle='#fff8e6';t.fillRect(18,18,700,70);t.fillStyle='#463d32';t.font='20px sans-serif';t.fillText('静态合成 · 实验坐标 '+p.x+','+p.y+' / 缩放 '+p.s,30,45);t.fillText('羊脚点 '+ax+','+py+'；底面 '+Math.round(46*p.s)+'×'+Math.round(14*p.s),30,73);a.append(h,c);root.append(a);return t;}
places.forEach((p,i)=>board('深度 '+(i+1)+' · 占位体在羊前（实验）',p));board('同一处 · 羊在占位体前（实验）',places[1],true,true);for(const [title,on]of [['未摆',false],['摆后',true],['收起',false]])board('同视角 · '+title,places[1],on,false);

const safe=board('实验安全包络 · 非正式碰撞区',places[1]);safe.fillStyle='rgba(205,135,35,.20)';safe.strokeStyle='#9b6122';safe.lineWidth=3;safe.beginPath();safe.ellipse(480,500,65,32,0,0,Math.PI*2);safe.fill();safe.stroke();safe.setLineDash([8,5]);safe.strokeStyle='#3f6b84';safe.beginPath();safe.ellipse(705,592,148,52,0,0,Math.PI*2);safe.stroke();safe.strokeStyle='#81684d';safe.beginPath();safe.moveTo(285,430);safe.lineTo(375,590);safe.stroke();safe.setLineDash([]);safe.fillStyle='#fff8e6';safe.fillRect(18,640,1000,58);safe.fillStyle='#463d32';safe.font='18px sans-serif';safe.fillText('橙：实验包络130×64；蓝：既有池塘参考椭圆；棕：门前路径示意边缘',28,663);safe.fillText('仅图面关系，尚未核验真实路宽、身体余量或避让；不能当正式碰撞区',28,687);
